version: "3.2"
services:
  redis:
    image: redis:7.0.5-alpine
    restart: always
    ports:
      - {{REDIS_PORTS_PROT}}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass {{REDIS_ADMIN_PASSWORD}}
    volumes:
    - ./redis/data/:/data